name: 'Hello World'
description: 'Greet someone'
inputs:
  VAULT_ROLE_ID:
    description: 'Vault secret id'
    required: true 
  VAULT_SECRET_ID: 
    description: 'vault secret id'
    required: true 
  REPO: 
    description: 'docker repository URL'
    required: true
  
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.2
      id: secrets
      with:
        url: https://vault.k8sdemo.tk
        method: approle
        roleId: ${{ inputs.VAULT_ROLE_ID }}
        secretId: ${{ inputs.VAULT_SECRET_ID }}
        secrets: |
          kv/data/${{ env.REPO }}/v2 username | USERNAME  ;
          kv/data/${{ env.REPO }}/v2 password | PASSWORD 
    - name: docker login
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.REPO }}
        username: ${{ steps.secrets.outputs.USERNAME }}
        password: ${{ steps.secrets.outputs.PASSWORD }}