name: 'Hello World'
description: 'Greet someone'
inputs:
  VAULT_ROLE_ID:
    description: 'Vault secret id'
    required: true 
  VAULT_SECRET_ID: 
    description: 'vault secret id'
    required: true 
  DOCKER_REGISTRY: 
    description: 'docker registry URL'
    required: false
    default: ''
  secrets:
    description: 'vault secrets keys'
    required: true
    default: ''
  
outputs:
  USERNAME:
    description: "docker username"
    value: ${{ steps.secrets.outputs.USERNAME }}
  PASSWORD: 
    description: "docker password"
    value: ${{ steps.secrets.outputs.PASSWORD }}
runs:
  using: "composite"
  steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.2
      id: secrets
      with:
        url: https://vault.k8sdemo.tk
        method: approle
        roleId: ${{ inputs.VAULT_ROLE_ID }}
        secretId: ${{ inputs.VAULT_SECRET_ID }}
        secrets: ${{ inputs.secrets }}
        # secrets: |
        #   kv/${{ inputs.DOCKER_REGISTRY }}/v2 username | USERNAME  ;
        #   kv/${{ inputs.DOCKER_REGISTRY }}/v2 password | PASSWORD 
    - name: docker login
      uses: docker/login-action@v2
      with:
        # registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ steps.secrets.outputs.USERNAME }}
        password: ${{ steps.secrets.outputs.PASSWORD }}